version: "2.2"
services:
  owl-vit-app:
    shm_size: '8gb'
    runtime: nvidia
    cap_add:
      - NET_ADMIN
    build:
      context: .
      args:
        IMAGE: supervisely/base-py-sdk:6.69.68
    ports:
      - "8888:22"
    volumes:
      - ".:/root/owl-vit-app"
      - "../supervisely/supervisely:/root/owl-vit-app/supervisely"
      - "../../supervisely.env:/root/supervisely.env"
